sheet: "Подгузники детские"
sku_header: "sku"             # как называется колонка со SKU в листе
headers:
  - sku
  - Название товара
  - Бренд
  - Цвет
  - Описание
  - Полное наименование товара
  - Тип подгузников
  - Весовая группа
  - Количество предметов в упаковке
  - Срок годности
  - Страна производства
  - Форма упаковки
  - Комплектация
  - Упаковка
  - Длина упаковки
  - Ширина упаковки
  - Высота упаковки
  - Вес товара с упаковкой (г)

# поле из MPStats (подстрока в param_names/других полях) -> в какую колонку писать
field_mapping:
  Название товара: Название товара
  Бренд: Бренд
  Цвет: Цвет
  Описание: Описание
  Полное наименование товара: Полное наименование товара
  Тип подгузников: Тип подгузников
  Весовая группа: Весовая группа
  Количество предметов в упаковке: Количество предметов в упаковке
  Срок годности: Срок годности
  Страна производства: Страна производства
  Форма упаковки: Форма упаковки
  Комплектация: Комплектация
  Упаковка: Упаковка
  Длина упаковки: Длина упаковки
  Ширина упаковки: Ширина упаковки
  Высота упаковки: Высота упаковки
  Вес товара с упаковкой: Вес товара с упаковкой (г)
