sheet: "Влажные салфетки"
sku_header: "sku"
headers:
  - sku
  - Название товара
  - Бренд
  - Цвет
  - Описание
  - Полное наименование товара
  - Состав
  - Количество предметов в упаковке
  - Действие
  - Возрастные ограничения
  - Назначение косметического средства
  - Срок годности
  - Страна производства
  - Упаковка
  - Комплектация
  - Раздел меню
  - Длина упаковки
  - Ширина упаковки
  - Высота упаковки
  - Вес товара с упаковкой (г)
field_mapping:
  Название товара: Название товара
  Бренд: Бренд
  Цвет: Цвет
  Описание: Описание
  Полное наименование товара: Полное наименование товара
  Состав: Состав
  Количество предметов в упаковке: Количество предметов в упаковке
  Количество предметов: Количество предметов в упаковке
  Действие: Действие
  Возрастные ограничения: Возрастные ограничения
  Назначение косметического средства: Назначение косметического средства
  Срок годности: Срок годности
  Страна производства: Страна производства
  Упаковка: Упаковка
  Комплектация: Комплектация
  Раздел меню: Раздел меню
  Длина упаковки: Длина упаковки
  Ширина упаковки: Ширина упаковки
  Высота упаковки: Высота упаковки
  Вес товара с упаковкой: Вес товара с упаковкой (г)
