sheet: "Прокладки гигиенические"
sku_header: "sku"
headers:
  - sku
  - Название товара
  - Бренд
  - Цвет
  - Описание
  - Полное наименование товара
  - Состав
  - Количество предметов в упаковке
  - Назначение прокладок
  - Страна производства
  - Упаковка
  - Комплектация
  - Раздел меню
  - Количество капель (шт.)
  - Длина упаковки
  - Ширина упаковки
  - Высота упаковки
  - Вес товара с упаковкой (г)
field_mapping:
  Название товара: Название товара
  Бренд: Бренд
  Цвет: Цвет
  Описание: Описание
  Полное наименование товара: Полное наименование товара

  Состав: Состав
  Материал: Состав
  Материал изделия: Состав

  Количество предметов в упаковке: Количество предметов в упаковке
  Количество предметов: Количество предметов в упаковке
  Кол-во предметов: Количество предметов в упаковке
  Количество, шт: Количество предметов в упаковке

  Назначение прокладок: Назначение прокладок
  Тип прокладок: Назначение прокладок
  Назначение: Назначение прокладок

  Страна производства: Страна производства
  Страна-изготовитель: Страна производства

  Упаковка: Упаковка
  Тип упаковки: Упаковка

  Комплектация: Комплектация
  Состав комплекта: Комплектация

  Раздел меню: Раздел меню
  Категория: Раздел меню

  Количество капель: Количество капель (шт.)
  Кол-во капель: Количество капель (шт.)
  Степень впитываемости: Количество капель (шт.)

  Длина упаковки: Длина упаковки
  Длина, см: Длина упаковки

  Ширина упаковки: Ширина упаковки
  Ширина, см: Ширина упаковки

  Высота упаковки: Высота упаковки
  Высота, см: Высота упаковки

  Вес товара с упаковкой: Вес товара с упаковкой (г)
  Вес с упаковкой: Вес товара с упаковкой (г)
  Вес брутто: Вес товара с упаковкой (г)
