sheet: "Трусы одноразовые"
sku_header: "sku"
headers:
  - sku
  - Название товара
  - Бренд
  - Цвет
  - Описание
  - Полное наименование товара
  - Количество предметов в упаковке (шт.)
  - Состав
  - Назначение одноразового изделия
  - Страна производства
  - Модель трусов
  - Пол
  - Упаковка
  - Комплектация
  - Торговое наименование
  - Длина упаковки
  - Ширина упаковки
  - Высота упаковки
  - Вес товара с упаковкой (г)
field_mapping:
  Название товара: Название товара
  Бренд: Бренд
  Цвет: Цвет
  Описание: Описание
  Полное наименование товара: Полное наименование товара

  Количество предметов в упаковке (шт.): Количество предметов в упаковке (шт.)
  Количество предметов в упаковке: Количество предметов в упаковке (шт.)
  Количество предметов: Количество предметов в упаковке (шт.)
  Кол-во предметов: Количество предметов в упаковке (шт.)
  Количество, шт: Количество предметов в упаковке (шт.)

  Состав: Состав
  Материал: Состав
  Материал изделия: Состав

  Назначение одноразового изделия: Назначение одноразового изделия
  Назначение: Назначение одноразового изделия

  Страна производства: Страна производства
  Страна-изготовитель: Страна производства

  Модель трусов: Модель трусов
  Модель: Модель трусов

  Пол: Пол
  Для кого: Пол

  Упаковка: Упаковка
  Тип упаковки: Упаковка

  Комплектация: Комплектация
  Состав комплекта: Комплектация

  Торговое наименование: Торговое наименование
  ТН ВЭД / ТН: Торговое наименование

  Длина упаковки: Длина упаковки
  Длина, см: Длина упаковки

  Ширина упаковки: Ширина упаковки
  Ширина, см: Ширина упаковки

  Высота упаковки: Высота упаковки
  Высота, см: Высота упаковки

  Вес товара с упаковкой: Вес товара с упаковкой (г)
  Вес с упаковкой: Вес товара с упаковкой (г)
  Вес брутто: Вес товара с упаковкой (г)
